# Project Definition
name: MagnoNetworkingModule

options:
    bundleIdPrefix: com.kaiquemagno.netowrkmodule
    groupSortPosition: bottom
    generateEmptyDirectories: true

targets:
    MagnoNetwork:
        type: framework
        platform: [iOS, macOS, watchOS, tvOS]
        sources:
            - path: ./MagnoNetwork
        info:
            path: "./MagnoNetwork/Supporting Files/Info.plist"
        scheme:
            gatherCoverageData: true
            testTargets:
                - name: MagnoNetworkTests_${platform}
                - parallelizable: true
                - randomExecutionOrder: true
        settings:
            base:
                SWIFT_OBJC_BRIDGING_HEADER: ./MagnoNetwork/Supporting Files/MagnoNetwork.h
    MagnoNetworkSample:
        type: application
        platform: [iOS, macOS, watchOS, tvOS]
        sources:
            - path: ./MagnoNetworkSample
        info:
            path: "./MagnoNetworkSample/Supporting Files/Info.plist"
        dependencies:
            - target: MagnoNetwork_${platform}
    MagnoNetworkTests:
        type: bundle.unit-test
        platform: [iOS, macOS, watchOS, tvOS]
        sources:
            - path: ./MagnoNetworkTests
        info:
            path: "./MagnoNetworkTests/Supporting Files/Info.plist"
        dependencies:
            - target: MagnoNetworkTests_${platform}
       
settings:
    base:
        SWIFT_VERSION: 5.5
